### PR TITLE
HIVEMALL-22: Update news feed for next Apache release

### PR DESCRIPTION
**Pull request by Lewuathe**
see: https://issues.apache.org/jira/browse/HIVEMALL-22

### CODE REVIEW

**Comment by myui** [comment]
Merged https://github.com/apache/incubator-hivemall/commit/556503b1ac4d67bb8b0cb06e20afffdcaa8f5851 

Thank you for the contribution. Could you close this issue?

**Comment by myui** [comment]
hmm... It seems the contributor is not tracked on github.

When using github squash web UI, it was tracked https://github.com/apache/incubator-hivemall/commit/effe461446f2af84931901c112d542b8d2e69cfd though

**Comment by myui** [comment]
@Lewuathe Could you update the project site as well? Do you know the instructions?
You can use `bin/build_site.sh` to build the site.

git://git.apache.org/incubator-hivemall-site.git (asf branch)

**Comment by Lewuathe** [comment]
Thanks. I updated the site.
http://hivemall.incubator.apache.org/

**Comment by myui** [comment]
Good to hear that you can run a ASF development procedure :-)

**Pull request closed without merging**
