### PR TITLE
[HIVEMALL-31] [WIP] Change the branch of spark-2.0 to spark-2 and upgrade Spark to 2.1.0

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Change the branch of spark-2.0 to spark-2 and upgrade Spark to 2.1.0

## What type of PR is it?

 Improvement 

### What is the Jira issue?

https://issues.apache.org/jira/browse/HIVEMALL-31

Open an issue on Jira https://issues.apache.org/jira/browse/HIVEMALL

## How was this patch tested?

Existing tests

Please review http://hivemall.incubator.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by wangyum** [comment]
OK, I'm working on the test failed.

**Comment by maropu** [comment]
Thanks for you work! If finished, plz give me a heads-up.

**Comment by wangyum** [comment]
Remove the [QueryTest.checkJsonFormat](https://github.com/apache/incubator-hivemall/blob/v0.5-alpha.1/spark/spark-2.0/src/test/scala/org/apache/spark/sql/QueryTest.scala#L231), see [SPARK-17426](https://issues.apache.org/jira/browse/SPARK-17426)

**Comment by wangyum** [comment]
@maropu , Do not merge it. I will fix `XGBoostSuite` test fail after the Spring Festival.

**Comment by maropu** [comment]
yea, could you add `[WIP]` in this title?

**Comment by maropu** [comment]
Since this pr got stale, I fixed this in #35. Could you close this? I'm looking forward to seeing your continuous contributions.

**Pull request closed without merging**
