### PR TITLE
[HIVEMALL-179][SPARK] Support spark-v2.3

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr supported the latest spark-v2.3.

## What type of PR is it?
Improvement

## What is the Jira issue?
https://issues.apache.org/jira/projects/HIVEMALL/issues/HIVEMALL-179

## How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by maropu** [comment]
I was thinking we would drop the spark-2.0 support until the next release. ok? cc: @myui

**Comment by myui** [comment]
@maropu Yes, let's drop spark-2.0 support in the next release. Please do it in another ticket.

FYI supported Spark version in EMR.
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/images/emr-releases-5x.png

**Comment by myui** [comment]
CI failing due to `Failed to execute goal org.scalastyle:scalastyle-maven-plugin:0.8.0:check (default) on project hivemall-spark2.3: Failed during scalastyle execution: You have 8 Scalastyle violation(s). -> [Help 1]`

**Comment by myui** [comment]
@maropu Is this PR still WIP?

**Comment by maropu** [comment]
yea, I still need to have some checks on the v2.3 integration. If I finished, I'll ping you.

**Comment by maropu** [comment]
ok, ready to check. cc: @myui

**Comment by maropu** [comment]
ok.

**Comment by maropu** [comment]
merged to master

**Pull request closed without merging**
