### PR TITLE
[HIVEMALL-30] Increase -Xmx to -Xmx1536m to avoid OutOfMemoryError

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Increase -Xmx to -Xmx1536m to avoid `OutOfMemoryError`.

## How was this patch tested?

Manual tests

### CODE REVIEW

**Comment by myui** [comment]
@maropu Could you take a look at?

**Comment by maropu** [comment]
TravisCI always pass these tests though, why did you got the error? What's your environment?

**Comment by maropu** [comment]
Oh, I got you. So, how about setting these values along with the spark one (e.g., -mx3g)? See: https://github.com/apache/spark/blob/master/pom.xml#L2066

**Comment by maropu** [comment]
okya, LGTM cc: @myui

**Comment by myui** [comment]
@maropu BTW, why `mvn -q scalastyle:check test -Pspark-2.0" exited with 1` is happening?

**Comment by maropu** [comment]
@myui In running these tests, a spark context and unit tests work in the same JVM. The context uses at most 1g memory by default. So, in some conditions, the unit tests run short of memory, I think. If we set 3g at the value, the context uses 1g and the tests do 2g. That sounds fine to me.

**Comment by myui** [comment]
@maropu It seems GC is still happening for some cases...
```
HivemallFeatureOpsSuite:
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

`MaxPermGen=1024m` might be too big to need more space for others. Do we need `-MaxPermGen` ? Less parameter is better for configuring JVM.

**Comment by maropu** [comment]
@myui How about 512m? Sorry, but I forgot why I set that value there though, I checked the spark configure and I found that value is 512m.

**Comment by wangyum** [comment]
I'll try to set 512m.

**Comment by myui** [comment]
@wangyum @maropu Thanks. Merged with some modifications. Configuration for spark-1.6 should also be changed.

**Comment by maropu** [comment]
okay, thanks!

**Pull request closed without merging**
