### PR TITLE
[HIVEMALL-38][SPARK] Support ChangeFinderUDF in DataFrame/Spark

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr added APIs for `ChangeFinderUDF` in `HivemallOps`.

## What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/HIVEMALL-38

## How was this patch tested?
Added tests in `HivemallOpsSuite`.

### CODE REVIEW

**Comment by myui** [comment]
@maropu LGTM. Could you merge and close this one?

**Comment by myui** [comment]
BTW, documentation about sst/changefinder on dataframe would be helpful.

**Comment by myui** [comment]
@maropu Should I merge this PR? Or, wait for docs.

**Comment by maropu** [comment]
It's okay to merge

**Comment by myui** [comment]
@maropu sure. Merged! Thanks.

**Pull request closed without merging**
