### PR TITLE
HIVEMALL-22: Remove migrating repository alert

### PR DESCRIPTION
**Pull request by Lewuathe**
Since migration of repository has been done, we can remove migrating alert.

https://issues.apache.org/jira/browse/HIVEMALL-22

### CODE REVIEW

**Comment by myui** [comment]
Better to remain a news feed and `learn more` button on the top, instead of removing info.

**Comment by Lewuathe** [comment]
Thanks. I updated to announce repository migration.

**Comment by myui** [comment]
Could you please close this PR? PR from your fork is expected.
I cannot delete this branch while I removed it from ASF git :-(

Found a typo in
`Ou*t* project repository was migrated` => `Our project repository migrated`
BTW, it's a meaningless new feed. 

`We are planning the initial Apache release on Q1, 2017. <a href="/userguide/index.html"><button class="btn btn-primary" type="button">Learn more</button></a>`
would be a better message.

**Comment by Lewuathe** [comment]
Sure will do. Thanks.

**Pull request closed without merging**
