### PR TITLE
[HIVEMALL-120] Refactor on LDA/pLSA's mini-batch & buffered iteration logic

### PR DESCRIPTION
**Pull request by takuti**
## What changes were proposed in this pull request?

Refactor LDA/pLSA implementation for better mini-batch & buffered iteration logic

## What type of PR is it?

Refactoring

## What is the Jira issue?

https://issues.apache.org/jira/browse/HIVEMALL-120

## How was this patch tested?

Unit test & manual test on EMR

## How to use this feature?

Nothing has been changed

### CODE REVIEW

**Comment by takuti** [comment]
At first, I planned to replace `String[][] miniBatch` with things like `FeatureValue[][] miniBatch` similarly to the generic predictor implementation; that is, instead of dealing word counts as String e.g. "foo:10," I tried to represent them as `FeatureValue` for readability. However, since `PLSAPredictionUDAF` and `LDAPredictionUDAF` need to create OI for such word counts, Java standard string object is much more handy rather than `FeatureValue` objects.

Thus, document is still represented as an array (or list) of String for now.

**Comment by takuti** [comment]
@myui How do you think about adding `-tol` option as alias of the `-eps` option as I mentioned #87 
?

Also, if you have further ideas which improve the topic modeling UDFs, let you share and we discuss them here!

**Comment by myui** [comment]
@takuti Adding an alias `-tol` for `-eps` is a good idea.

**Comment by myui** [comment]
No need to replace `String[][] miniBatch`. It already using `FeatureVector` for parsing feature vectors as thus it accept the input format of Hivemall's feature vector.

**Comment by takuti** [comment]
> Adding an alias -tol for -eps is a good idea.

Sure.

>  it accept the input format of Hivemall's feature vector

Oh, it's not format matter by the way; `String` or `FeatureValue` in terms of type.

Current implementation repeatedly parses feature-value-formatted `String` at [HERE](https://github.com/takuti/incubator-hivemall/blob/bc4b9d3a13310d85c0fb4fc572d0338fefee0a8d/core/src/main/java/hivemall/topicmodel/AbstractProbabilisticTopicModel.java#L66-L69) for every time mini-batch is passed. If we directly pass a two-dimensional array of `FeatureValue` as word counts, we can avoid the unnecessary parse operations.

**Comment by myui** [comment]
ah, parsing multiple times could be avoided.

**Comment by myui** [comment]
Merged this PR. Create `[HIVEMALL-120-2]` for `-tol alias for -eps`.

**Comment by takuti** [comment]
Oh, you move very fast :) 

> -tol alias

Sure~

**Comment by takuti** [comment]
@myui Oh, you move very fast :) 

> -tol alias

Sure~

**Pull request closed without merging**
