### PR TITLE
[HIVEMALL-37][SPARK] Support  a SST-based change-point detector in DataFrame/Spark

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr supported a SST-based change-point detector as `sst` in `HivemallOps`.

## What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/HIVEMALL-37

## How was this patch tested?
Added a test in `HivemallOpsSuite`.

### CODE REVIEW

**Comment by myui** [comment]
LGTM. You can merge this PR.

**Comment by myui** [comment]
@maropu Could you add [SPARK] after [HIVEMALL-37]  in the title?

**Comment by maropu** [comment]
I'll merge this after #29 merged because they have conflicts between each other.

**Comment by myui** [comment]
@maropu LGTM. Please merge this PR and close the JIRA ticket.

**Comment by maropu** [comment]
Merged

**Pull request closed without merging**
