### PR TITLE
[HIVEMALL-85] Upgrade hivemall-xgboost's hadoop version to 2.6.5

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Upgrade hivemall-xgboost's hadoop version to 2.6.5

## What type of PR is it?

Improvement

## What is the Jira issue?

[HIVEMALL-85](https://issues.apache.org/jira/browse/HIVEMALL-85)

## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by maropu** [comment]
@wangyum Thanks for your continuous contributions! 
@myui do we have any reason to have a dependency with hadoop-core `0.20.2-cdh3u6`? I just used this dependency along with the other modules.

**Comment by myui** [comment]
@wangyum @maropu I think it's `provided` maven space and thus no need to change.
`provided` scope libraries are used just for compiling and not bundled in jars.

**Comment by maropu** [comment]
Yea, I know, but why we use cdh instead of hadoop community version?

**Comment by myui** [comment]
Mostly for historical reasons. Better to change the version dependencies to 2.4.0 but dependencies packages change and careful verification is required.

This branch changed the dependencies to 2.4.0 
https://github.com/myui/hivemall/tree/dev/yarnkit

**Comment by maropu** [comment]
@wangyum Why you select `2.6.5` in this pr? Any reason?

**Comment by wangyum** [comment]
Be consistent with the Spark.
https://github.com/apache/spark/blob/d76c18746bdd0908bae89e62da9667001be75624/pom.xml#L125

**Comment by myui** [comment]
We need to change whole dependencies to v2.4.0 following the way in https://github.com/myui/hivemall/tree/dev/yarnkit

File a ticket https://issues.apache.org/jira/browse/HIVEMALL-86

I would like to move the discussions to [Hivemall-86](https://issues.apache.org/jira/browse/HIVEMALL-86).

@wangyum Could you close this pull request?

**Comment by wangyum** [comment]
OK

**Comment by myui** [comment]
Thanks!

**Pull request closed without merging**
