### PR TITLE
[WIP] Implement SST-based change-point detector

### PR DESCRIPTION
**Pull request by myui**
This PR is based on [a pending PR](https://github.com/myui/hivemall/pull/356) by @takuti that is sent before Hivemall entered Apache Incubator.

See [JIRA](https://issues.apache.org/jira/browse/HIVEMALL-22
) for tracking the status of this issue.

---

### Sample table

| time | x |
| --: | --: |
| 1 | 182.478 |
| 2 | 176.231 |
| 3 | 183.917 |
| 4 | 177.798 |
| 5 | 165.469 |
| ... | ... |

(14398 points from [twitter data](https://blog.twitter.com/2015/introducing-practical-and-robust-anomaly-detection-in-a-time-series))
### Usage

``` sql
create temporary function sst as 'hivemall.anomaly.SingularSpectrumTransformUDF';
```

``` sql
SELECT
  time,
  -- x is double or array<double>
  -- sst(x) AS res
  sst(x, "-th 0.005") AS res
FROM
  twitter_timeseries
ORDER BY time ASC
;
```
### Results

```
7551    {"changepoint_score":0.00453049288071683,"is_changepoint":false}
7552    {"changepoint_score":0.004711244102524104,"is_changepoint":false}
7553    {"changepoint_score":0.004814871928978115,"is_changepoint":false}
7554    {"changepoint_score":0.004968089640799422,"is_changepoint":false}
7555    {"changepoint_score":0.005709056330104878,"is_changepoint":true}
7556    {"changepoint_score":0.0044279766655132,"is_changepoint":false}
7557    {"changepoint_score":0.0034694956722586268,"is_changepoint":false}
7558    {"changepoint_score":0.002549056569322694,"is_changepoint":false}
7559    {"changepoint_score":0.0017395109108403473,"is_changepoint":false}
7560    {"changepoint_score":0.0010629833145070489,"is_changepoint":false}
```

On the naive SVD-based implementation, elapsed time was about 20 sec. for the 14398 samples (vs. 10 sec on ChangeFinder)
### Observations

The change-point scores are much more stable compared to ChangeFinder, and change-point scores are always in [0, 1]. However, since the scores are quite noisy, too many change-points are detected. Smoothing scores like ChangeFinder is practically important.

In terms of running time, the naive SVD-based implementation is clearly inefficient. So, the Lanczos-based efficient variant should be supported.

### CODE REVIEW

**Comment by myui** [comment]
@takuti Could you provide a markdown documentation `docs/gitbook/anomaly/sst.md` for user guide? 

`gitbook serve` to check a user guide on a local machine.

**Comment by myui** [comment]
@takuti Could you review my changes?
https://github.com/apache/incubator-hivemall/pull/11/commits/e867b4557f7c8675ecebfd3eae082ca1ec395ea2

Applied refactoring based on my review comments.
https://github.com/myui/hivemall/pull/356/files/03b94bede2632eb94b2eab61bf87f0107d7aeb04

**Comment by myui** [comment]
@maropu @amaya382 

Support for `sst` UDF in Hivemall Spark module is very welcome.

**Comment by maropu** [comment]
@myui okay, I'll do.

**Comment by myui** [comment]
@maropu Thanks. `anomaly/changefinder` is another feature to add in v0.5. 
https://github.com/myui/hivemall/pull/333

The interface/functionality is similar to `sst`.

**Comment by takuti** [comment]
@myui Sorry for my late response to your review, and thanks for your backup. I move on to reviewing your modifications and gitbook documentation from now.

**Comment by myui** [comment]
@takuti Merged this PR. When you write markdown documents, please send a PR. 

Thanks.

**Pull request closed without merging**
