### PR TITLE
[HIVEMALL-242][HIVEMALL-241] Drop support for Spark 2.1 and Deprecate Java7 for packaging

### PR DESCRIPTION
**Pull request by myui**
## What changes were proposed in this pull request?

- Drop support for Spark 2.1
- Require Java8 for packaging, deprecating Java7 (class file compatibility is Java7 or later) 

Runtime Java compatibility: Java7 or later
Packaging/Compile-time Java compatibility: Java8 or later

## What type of PR is it?

Hot Fix

## What is the Jira issue?

https://issues.apache.org/jira/browse/HIVEMALL-242
https://issues.apache.org/jira/browse/HIVEMALL-241

## How was this patch tested?

unit tests, manual tests

## Checklist

- [x] Did you apply source code formatter, i.e., `./bin/format_code.sh`, for your commit?
- [ ] Did you run system tests on Hive (or Spark)?

### CODE REVIEW

**Comment by myui** [comment]
@maropu could you review this PR?

**Comment by myui** [comment]
confirmed class file versions contained in hivemall-all-0.6.0-incubating-SNAPSHOT.jar.

`find . -name "*.class" | xargs javap -v | grep "major version" | awk '{print $3 - 44 }' | sort | uniq`
> 5
> 6
> 7

**Comment by maropu** [comment]
Looks good to me!

**Comment by myui** [comment]
Will add verifier in pom.xml to check minimum class file compatibility to Java 7 (compile/packaging requires Java 8 or later though).

https://stackoverflow.com/questions/25014585/how-to-check-that-all-maven-dependencies-are-compiled-for-java-6

**Pull request closed without merging**
