### PR TITLE
[HIVEMALL-84-2] Fix docker

### PR DESCRIPTION
**Pull request by amaya382**
## What changes were proposed in this pull request?

Fix docker (https://github.com/apache/incubator-hivemall/pull/68#issuecomment-297029602)

## What type of PR is it?

Bug Fix

## What is the Jira issue?

[HIVEMALL-84](https://issues.apache.org/jira/browse/HIVEMALL-84)

## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by myui** [comment]
@amaya382 build of hivemall better to be optional in the document. Include ready-to-use jars on docker image.

I think Docker file should invoke `bin/build.sh` to create jars before `ln -s`.
https://github.com/apache/incubator-hivemall/blob/master/resources/docker/Dockerfile#L45

**Comment by amaya382** [comment]
@myui I've wanted to write as option explicitly but it makes doc complex. because if use data volume (probably most frequent use case), building becomes a must. so in fact, it's necessary to build.
if distribute via dockerhub, we can divide use prebuild image (for users, don't need to build hivemall) and use from source (for developers, need to build hivemall), and can write easy document.
Wait for dockerhub support or not?

> I think Docker file should invoke bin/build.sh to create jars before ln -s
what will change?

**Comment by myui** [comment]
@amaya382 

> what will change?

`${HIVEMALL_PATH}/target/hivemall-core-${HIVEMALL_VERSION}-with-dependencies.jar` is missing before building hivemall.

**Comment by amaya382** [comment]
Now blocked by [HIVEMALL-100](https://issues.apache.org/jira/browse/HIVEMALL-100)

**Comment by myui** [comment]
@amaya382 Merged with modidications. Thanks!

**Pull request merged**
