### PR TITLE
[HIVEMALL][SPARK][WIP] Fix Spark-related artifact issues

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
A objective of this pr is to fix artifact to release hivemall-v0.5.0 in ASF.
TODO
 - Update [the Release Guide](https://github.com/apache/incubator-hivemall/blob/master/src/site/markdown/release-guide.md) for Spark modules.

## What type of PR is it?

Bug Fix

### CODE REVIEW

**Comment by myui** [comment]
Ah, I'm planning to revert this commit https://github.com/apache/incubator-hivemall/commit/1e940aff316b1a91484ad08ba286492892b32d07 of v0.5.0 branch for rc2 release.

```
git checkout v0.5.0
git reset --hard HEAD^
```

0.5.1-SNAPSHOT is for next development iteration. No need to do it in v0.5.0 branch; however, Maven release plugin sets the development version.

**Comment by maropu** [comment]
yea, NVM. A main target of this pr is to solve all the issue for the upcoming releases.

**Comment by myui** [comment]
Better to use jenv, scalaenv for java/scala compiler section in the document.

**Comment by maropu** [comment]
See #131

**Pull request closed without merging**
