### PR TITLE
[HIVEMALL-75] Support Sparse Vector Format as the input of RandomForest

### PR DESCRIPTION
**Pull request by myui**
## What changes were proposed in this pull request?

Supported sparse vector as the input of RandomForest.

## What type of PR is it?

Improvement

## What is the Jira issue?

https://issues.apache.org/jira/browse/HIVEMALL-75

## How was this patch tested?

unit test and manual test

### CODE REVIEW

**Comment by myui** [comment]
Need to reduce memory usage for a large sparse input. WIP...

```
Caused by: java.lang.OutOfMemoryError: Java heap space
        at smile.sort.QuickSort.sort(QuickSort.java:576)
        at hivemall.smile.utils.SmileExtUtils.sort(SmileExtUtils.java:135)
        at hivemall.smile.classification.RandomForestClassifierUDTF.train(RandomForestClassifierUDTF.java:340)
        at hivemall.smile.classification.RandomForestClassifierUDTF.close(RandomForestClassifierUDTF.java:291)
        at org.apache.hadoop.hive.ql.exec.UDTFOperator.closeOp(UDTFOperator.java:152)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:682)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:696)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:696)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:696)
        at org.apache.hadoop.hive.ql.exec.tez.MapRecordProcessor.close(MapRecordProcessor.java:398)
        at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:186)
        ... 14 more
```

**Comment by myui** [comment]
@maropu

To reduce memory consumption, I'm considering to replace `int[][] order` with `CompressedIntStream[]`.

https://github.com/myui/incubator-hivemall/blob/7dba520cb709326edffb945dd925876433200a93/core/src/main/java/hivemall/smile/classification/RandomForestClassifierUDTF.java#L343

`CompressedIntStream` should support streaming construction and should support streaming decompression in 
https://github.com/myui/incubator-hivemall/blob/7dba520cb709326edffb945dd925876433200a93/core/src/main/java/hivemall/smile/classification/DecisionTree.java#L551

Any good algorithm or library for fast integer sequence compression/decompression?

**Comment by maropu** [comment]
`blosc` provides random access (of course, you can read data from the head to the end) on compressed data though, there is no java wrapper in the official: http://blosc.org/. As another option, you can use bitshuffle + snappy in `snappy-java` (this is not differential coding though). But, in this case, you need to write a bit code to compress data block-by-block by yourself. Then, you could access the compressed data from the head block-by-block. That is, my answer is that AFAIK there is no existing library for your case.

**Comment by myui** [comment]
@maropu In this case, Random Access is not a requirement.

An option is using Deflate and DataInputStream/DataOutputStream. However, fast deserialization is preferred.

Compressing int[] to byte[] and decompressing the compressed byte[] by sequential `readInt()`.

**Comment by myui** [comment]
@maropu introduced compressed `IntStream` for sparse inputs.

**Comment by myui** [comment]
Column Major Accesses on CSRMatrix is too slow ...

3bc3d325797fcea88334268aed393a6f

**Comment by myui** [comment]
[DoKMatrix](https://github.com/myui/incubator-hivemall/blob/7b6e9831410ba811e511c9a4068690650d8723c8/core/src/main/java/hivemall/matrix/DoKMatrix.java#L161) is slow at [swap](https://github.com/myui/incubator-hivemall/blob/7b6e9831410ba811e511c9a4068690650d8723c8/core/src/main/java/hivemall/smile/utils/SmileExtUtils.java#L238) ...

cd203a38ac45b8ce9625ba8d7e093142

**Comment by myui** [comment]
[`CSRMatrix#eachInRow`](https://github.com/myui/incubator-hivemall/blob/50df900b546773721d3977a53a9a7190de6abd37/core/src/main/java/hivemall/smile/classification/DecisionTree.java#L440) is too slow ...

6d749df044b24b53907e24cb7071afd0

**Comment by myui** [comment]
Refactored to use `RoaringBitmap` and `IntReservoirSampler`.

d520699f0e299405e577936273ac14c3

**Comment by myui** [comment]
Need to sync with the current Smile's up-to-date prediction scheme for the better accuracy.

https://github.com/haifengl/smile/commit/444d8bb916379f4d53d87be9ae1071aebcaab76d
https://github.com/szilard/benchm-ml/issues/32

**Comment by myui** [comment]
Merged. Documentation and model conversion pull requests follows in [HIVEMALL-75-2]

**Pull request closed without merging**
