### PR TITLE
[HIVEMALL-26][SPARK] Make docs for regression and binary classification

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr added docs for hivemall-on-spark.

## What type of PR is it?
Documentation

## What is the Jira issue?
https://issues.apache.org/jira/browse/HIVEMALL-26

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by maropu** [comment]
Updated

**Comment by myui** [comment]
@maropu Thanks. LGTM. Merged w/ modifications.

**Comment by myui** [comment]
Update the project site
http://hivemall.incubator.apache.org/userguide/spark/binaryclass/

**Comment by maropu** [comment]
Many thanks!

**Pull request closed without merging**
