### PR TITLE
[HIVEMALL-103][Spark] Upgrade spark-v2.1.0 to v2.1.1

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr upgraded spark-v2.1.0 to v2.1.1.

## What type of PR is it?
Improvement

## What is the Jira issue?
https://issues.apache.org/jira/browse/HIVEMALL-103

## How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by myui** [comment]
@maropu LGTM. Could you merge this PR into master?

**Comment by maropu** [comment]
ok

**Comment by maropu** [comment]
merged to master.

**Comment by myui** [comment]
Thanks!

**Pull request closed without merging**
