### PR TITLE
[Spark] Update gitbook for top_k_join

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
Added some descriptions for `top_k_join`.

## What type of PR is it?
Documentation

### CODE REVIEW

**Comment by myui** [comment]
@maropu LGTM. Please merge this PR and close the JIRA ticket.

Also, please update https://github.com/apache/incubator-hivemall-site as well.

**Comment by maropu** [comment]
Do we need to update the site every gitbook modified?

**Comment by maropu** [comment]
Merged

**Comment by myui** [comment]
@maropu unfortunately, we have to do manually. We cannot use github hooks in ASF repository.

**Comment by maropu** [comment]
What I meant is that it's enough to update them just before Apache GA releases?

**Comment by myui** [comment]
@maropu anytime you want but we need to make the project site up-to-date for each release.

**Comment by maropu** [comment]
okay, I got it.

**Comment by myui** [comment]
@maropu Could you add missing license header to updated `*.md`?
Currently, travis CI is failing due to that.

Please perform ` mvn license:check; mvn license:format`.

**Comment by maropu** [comment]
It seems your commit makes test fail, Why do we need `misc.md`? https://github.com/apache/incubator-hivemall/commit/4909deda546946a66de31195b9a3eaa120382c50#diff-3b8b2ffac8e90873350a4d049de9b854

**Comment by myui** [comment]
Fixed in https://github.com/apache/incubator-hivemall/commit/fdb4dd86965f8b79f6dc257a783e683c93fadc43

It's required for gitbook menu http://hivemall.incubator.apache.org/userguide/spark/misc/misc.html

**Comment by maropu** [comment]
okay, thanks

**Pull request closed without merging**
