### PR TITLE
[HIVEMALL-31][SPARK] Support Spark-v2.1.0

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
Support the latest Spark release.

## What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/HIVEMALL-31

## How was this patch tested?
Run the existing tests.

### CODE REVIEW

**Comment by myui** [comment]
@maropu test is failing for v2.1.

```
Saving to outputFile=/home/travis/build/apache/incubator-hivemall/spark/spark-common/target/scalastyle-output.xml
Processed 3 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 667 ms
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/QueryTest.scala message=Header does not match expected text line=2
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/catalyst/plans/PlanTest.scala message=Header does not match expected text line=2
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala message=import.ordering.wrongOrderInGroup.message line=22 column=0
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala message=import.ordering.wrongOrderInGroup.message line=30 column=0
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/hive/test/TestHiveSingleton.scala message=Header does not match expected text line=2
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/test/SQLTestData.scala message=Header does not match expected text line=2
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/test/SQLTestUtils.scala message=Header does not match expected text line=2
error file=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/src/test/scala/org/apache/spark/sql/test/VectorQueryTest.scala message=import.ordering.missingEmptyLine.message line=25 column=0
Saving to outputFile=/home/travis/build/apache/incubator-hivemall/spark/spark-2.1/target/scalastyle-output.xml
Processed 25 file(s)
Found 8 errors
Found 0 warnings
Found 0 infos
Finished in 2737 ms
[ERROR] Failed to execute goal org.scalastyle:scalastyle-maven-plugin:0.8.0:check (default-cli) on project hivemall-spark: Failed during scalastyle execution: You have 8 Scalastyle violation(s). -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hivemall-spark
The command "mvn -q scalastyle:check test -Pspark-2.1" exited with 1.
```

**Comment by maropu** [comment]
I'll look into this failure.

**Comment by myui** [comment]
@maropu LGTM. Please merge this PR and close the JIRA issue.

**Comment by myui** [comment]
BTW, you can close https://github.com/apache/incubator-hivemall/pull/23 as well.
`Close #35, #23: xxxx xxxx`

**Comment by maropu** [comment]
Merged

**Comment by myui** [comment]
Thanks!

**Pull request closed without merging**
