### PR TITLE
[HIVEMALL-35] Remove unnecessary implicit conversions in HivemallUtils

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr removed entries for implicit conversion in `HivemallUtils`.

## What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/HIVEMALL-35

### CODE REVIEW

**Comment by myui** [comment]
@maropu LGTM. Please merge this PR and close JIRA issue as fixed.

**Comment by maropu** [comment]
I wait for tests finished

**Comment by maropu** [comment]
I made a pr for this flaky test failure in #28, so I'll merge this.

**Comment by maropu** [comment]
Merged

**Pull request closed without merging**
